function rec = py_decode(q)
%rec = PY_DECODE Returns the decoded masses configuration.
% Assumes a model and connectivity (edge_index & edge_attr) are in python workspace.

rec = pyrun([ ...
    "emb = torch.Tensor(np.array(q))" ...
    "with torch.no_grad():" ...
    "   r = model.decode(emb, d).view(view_size)" ...
    "   r = r.numpy()"], ...
    "r", ...
    q=q);

rec = double(rec);

end