function rec = py_decode(q)

rec = pyrun([ ...
    "emb = torch.Tensor(np.array(q))" ...
    "with torch.no_grad():" ...
    "   r = model.decode(emb, d).view(view_size)" ...
    "   r = r.numpy()"], ...
    "r", ...
    q=q);

rec = double(rec);

end