function [xi, dxi] = py_encoder_dyn(x, dx)
%[xi, xi_dot] = PY_ENCODER_DYN 
%

[xi, dxi] = pyrun([ ...
    "d.pos = torch.Tensor(np.array(x))" ...
    "dx = np.array(dx)" ...
    "with torch.no_grad(): xi = model.encode(d)" ...
    "xi = xi.numpy().squeeze()" ...
    "j = jacobian(modelf_j_enc, d.pos).detach().numpy()" ...
    "dxi = j @ dx"], ...
    ["xi", "dxi"], ...
    x=x, dx=dx);

xi = squeeze(double(xi)');
dxi = double(dxi);

end