function py_load_model(sys_idx, model_name)
%PY_LOAD_MODEL Load the PyTorch model into the python workspace.

pyrun([ ...
    "from utils.data import load_model" ...
    "model = load_model(sys, name)" ...
    "model.eval()" ...
    "view_size = num_masses * in_channels" ...
    "def modelf_j(e):" ...
    "   return model.decode(e, d).view(view_size)" ...
    "def modelf_h(i):" ...
    "   return lambda e: model.decode(e, d).view(view_size)[i]"], ...
    "", ...
    sys = sys_idx, name = model_name);

end