function py_load_model(config_file, model_file)
%PY_LOAD_MODEL Load the pytorch model into the python workspace.

pyrun([ ...
    "from utils.misc import from_dictionary" ...
    "model = from_dictionary(cf)" ...
    "model.load_state_dict(" + ...
        "torch.load(mf, map_location=torch.device('cpu')))" ...
    "model.eval()" ...
    "view_size = num_masses * in_channels" ...
    "def modelf_j(e):" ...
    "   return model.decode(e, d).view(view_size)" ...
    "def modelf_j_enc(x):" ...
    "   d.pos = x" ...
    "   return model.encode(d)" ...
    "def modelf_h(i):" ...
    "   return lambda e: model.decode(e, d).view(view_size)[i]"], ...
    "", ...
    cf = config_file, mf = model_file);

end