function py_load_data(pos, adj, attr, groups)
%PY_LOAD_DATA Load the system's edge index and edge attributes (PyG) into
%python workspace.

pyrun([ ...
    "from torch_geometric.data import Data" ...
    "from torch_geometric.transforms import ToUndirected" ...
    "ei = torch.LongTensor(np.array(ei)).T - 1" ...
    "ea = torch.Tensor(np.array(ea))" ...
    "gr = torch.LongTensor(np.array(gr))" ...
    "x = torch.Tensor(np.array(x))" ...
    "d = Data(pos=x, edge_index=ei, edge_attr=ea, groups=gr, rest=x)" ...
    "d = ToUndirected()(d)" ...
    "d.edge_attr = None" ...
    "num_masses = x.shape[0]" ...
    "in_channels = x.shape[1]"], ...
    "", ...
    x=pos, ei=adj, ea=attr, gr=groups);

end